url-shortener:
  ribbon:
    eureka:
      enabled: false
    listOfServers: http://localhost:8080,http://localhost:8081,http://localhost:8082
    ServerListRefreshInterval: 2000

server:
  port: 9090